### ISSUE TITLE
Tenemos projectos similares

### ISSUE THREAD

**Issue by MarianoOG** [dmr-mex/UniAbierta#1]
Hola!

Soy parte de una organización sin fines de lucro de la Cuidad de México llamada [Fundación Kichihua A.C.](https://www.kichihua.com), nos dedicamos a crear experiencias educativas. Veo que tu descripción del proyecto comparte varios puntos de nuestra ideología así como intereses. Después de tener varios problemas tratando de hacer varios tipos de programas y actividades por fin empezamos a tener rumbo. 

Actualmente estamos desarrollando un [curso de programación y otro de pensamiento lógico matemático](https://www.kichihua.com/cursos/). Al mismo tiempo damos consultoría a pequeños negocios (capacitación) así como conferencias y talleres de estilos parentales, inteligencias multiples, creatividad.

Espero podamos platicar más a fondo por si podemos colaborar en el desarrollo de los cursos, yo soy el coordinador de ese proyecto. 

Mariano Orozco García
* Twitter: www.twitter.com/Mariano_OG
* Correo: mariano@kichihua.com

**Comment by dmr-mex** [comment]
Hola!

un gusto conocer creadores con actividades educativas.

me gustaria empezar creando contenidos educativos y adquirir mas adeptos,
solo que tambien debo ocupar mis esfuerzos en el lucro.

Soy programador y he creado sitios web, sistemas educativos, etc.
Estoy alejado de las actividades en internet por mis ocupaciones pero
en cuanto recupere mis recursos (trabajo) puedo poner un sistema web,
servidor propio, desarrollar varios proyectos, dar cursos, diseñar
sistemas, etc.

Podriamos unirnos, formar campañas de apoyo y recibir donaciones,
patrocinios, etc.
Ejemplo:

https://docs.google.com/forms/d/1s8vf4P08AiKNVxymhMNCyfBm4xBVY7n9BK_bAPTsz0s/prefill

**Comment by MarianoOG** [comment]
Que bien!

Si, por ahora lo importante es crear contenidos educativos y gente interesada en participar y tomar el curso. La idea es crear todo el material de forma gratuita pero si quieres utilizar dicho material para dar clases particulares o asesorias es totalmente posible.

¿Qué sistemas educativos has creado? Es algo en lo que hemos pensado mucho, sería de mucha ayuda conocer algunos ejemplos más.

Sobre donaciones y patrocinios estamos trabajando en ello también en la fundación lo primero por medio de [patreon](https://patreon.com/kichihua) y lo segundo viendo varios programas. 

Seguimos en etapa de construcción y diseño por lo que tomará tiempo todo ello.

Si tienes algún método de contacto no dudes en enviarlo ojala se pueda llegar a algo interesante. Que tengas un excelente día.
